import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import HomeHeader from "@/ui/header";

const mainFont = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${mainFont.variable} bg-slate-100`}>{children}
      <HomeHeader />
      </body>
    </html>
  );
}
